#!/usr/bin/env bun

import fs from "node:fs"
import path from "node:path"
import { fileURLToPath, pathToFileURL } from "node:url"
import { discoverExpertSquadPayloadPackages } from "./generate-expert-squad-payload"

// The published website already carries a reviewed Chinese projection of every bundled Expert Squad.
// Market and catalog discovery are byte-identical English package sources, so a Chinese request scores
// zero against them. This module lifts the reviewed website translations into a bounded, search-only
// projection. It never enters a package payload, so no package digest changes.

const PRIMARY_LIMIT = 1_000
const DETAIL_ENTRY_LIMIT = 240
const DETAIL_ENTRY_COUNT = 32

interface SquadTranslation {
  label: string
  description: string
  selectorSummary: string
  agents: Record<string, { label: string; description?: string }>
  workflows: Record<string, { label: string; description: string; nodes: Record<string, string> }>
}

export function resolveExpertSquadSearchLocalizationModulePath(repoRoot: string): string {
  return path.join(repoRoot, "packages", "opencorvus", "generated", "expert-squad-search-localization.ts")
}

function localizationSourceDirectory(repoRoot: string): string {
  return path.join(repoRoot, "packages", "web", "src", "content")
}

async function loadTranslations(repoRoot: string): Promise<Map<string, SquadTranslation>> {
  const directory = localizationSourceDirectory(repoRoot)
  const files = fs
    .readdirSync(directory)
    .filter((entry) => /^public-market-zh-.+\.ts$/u.test(entry) && entry !== "public-market-zh-types.ts")
    .sort()
  if (files.length === 0) {
    throw new Error(`Expert squad search localization found no translation modules in ${directory}`)
  }
  const translations = new Map<string, SquadTranslation>()
  for (const file of files) {
    const module = (await import(pathToFileURL(path.join(directory, file)).href)) as Record<string, unknown>
    for (const value of Object.values(module)) {
      if (!value || typeof value !== "object") continue
      for (const [key, translation] of Object.entries(value as Record<string, SquadTranslation>)) {
        if (!key.includes("/")) continue
        if (translations.has(key)) {
          throw new Error(`Expert squad search localization received duplicate translation key ${key}`)
        }
        translations.set(key, translation)
      }
    }
  }
  return translations
}

function bounded(value: string | undefined, limit: number): string {
  return (value ?? "").replace(/\s+/gu, " ").trim().slice(0, limit)
}

function detailEntries(translation: SquadTranslation): string[] {
  const entries: string[] = []
  for (const agent of Object.values(translation.agents)) {
    entries.push(bounded(`${agent.label} ${agent.description ?? ""}`, DETAIL_ENTRY_LIMIT))
  }
  for (const workflow of Object.values(translation.workflows)) {
    entries.push(bounded(`${workflow.label} ${workflow.description}`, DETAIL_ENTRY_LIMIT))
    for (const node of Object.values(workflow.nodes)) entries.push(bounded(node, DETAIL_ENTRY_LIMIT))
  }
  return [...new Set(entries.filter(Boolean))].slice(0, DETAIL_ENTRY_COUNT)
}

export async function renderExpertSquadSearchLocalizationModule(repoRoot: string): Promise<string> {
  const packages = await discoverExpertSquadPayloadPackages(repoRoot)
  const translations = await loadTranslations(repoRoot)
  const blocks: string[] = []

  for (const pkg of packages) {
    const key = `${pkg.namespace}/${pkg.id}`
    const translation = translations.get(key)
    if (!translation) {
      throw new Error(`Expert squad search localization has no reviewed translation for ${key}`)
    }
    const primary = [
      bounded(translation.label, PRIMARY_LIMIT),
      bounded(translation.description, PRIMARY_LIMIT),
      bounded(translation.selectorSummary, PRIMARY_LIMIT),
    ].filter(Boolean)
    if (primary.length !== 3) {
      throw new Error(`Expert squad search localization received an incomplete translation for ${key}`)
    }
    const detail = detailEntries(translation)
    blocks.push(
      [
        `  ${JSON.stringify(key)}: {`,
        `    primary: [${primary.map((entry) => JSON.stringify(entry)).join(", ")}],`,
        `    detail: [${detail.map((entry) => JSON.stringify(entry)).join(", ")}],`,
        "  },",
      ].join("\n"),
    )
  }

  return [
    "// Auto-generated by packages/opencorvus/script/generate-expert-squad-search-localization.ts. Do not edit.",
    "// Search-only localized projection of the bundled Expert Squads, lifted from the reviewed public",
    "// market translations. These strings never enter a package payload and never change a package digest.",
    "",
    "export interface ExpertSquadSearchLocalization {",
    "  readonly primary: readonly string[]",
    "  readonly detail: readonly string[]",
    "}",
    "",
    "export const expertSquadSearchLocalizations: Readonly<Record<string, ExpertSquadSearchLocalization>> = {",
    ...blocks,
    "}",
    "",
  ].join("\n")
}

export async function generateExpertSquadSearchLocalizationModule(repoRoot: string): Promise<string> {
  const modulePath = resolveExpertSquadSearchLocalizationModulePath(repoRoot)
  const content = await renderExpertSquadSearchLocalizationModule(repoRoot)
  const current = await fs.promises.readFile(modulePath, "utf8").catch((error: NodeJS.ErrnoException) => {
    if (error.code === "ENOENT") return undefined
    throw error
  })
  if (current !== content) await fs.promises.writeFile(modulePath, content)
  return modulePath
}

async function main(): Promise<void> {
  const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../..")
  const modulePath = await generateExpertSquadSearchLocalizationModule(repoRoot)
  console.log(`Generated ${path.relative(repoRoot, modulePath).replaceAll(path.sep, "/")}`)
}

if (import.meta.main) {
  await main()
}
