import { Database as BunDatabase } from "bun:sqlite"
import { createHash } from "node:crypto"
import { SCHEMA_DDL } from "./ddl"

type SchemaObjectShape = Map<string, string>

function queryAllFinalized<TResult>(sqlite: BunDatabase, sql: string): TResult[] {
  const statement = sqlite.query<TResult, []>(sql)
  let rows: TResult[] | undefined
  let operationFailure: unknown
  try {
    rows = statement.all()
  } catch (error) {
    operationFailure = error
  }
  try {
    statement.finalize()
  } catch (finalizeFailure) {
    if (operationFailure !== undefined) {
      throw new AggregateError([operationFailure, finalizeFailure], "SQLite schema query and finalization both failed", {
        cause: operationFailure,
      })
    }
    throw finalizeFailure
  }
  if (operationFailure !== undefined) throw operationFailure
  return rows as TResult[]
}

export function readSchemaObjectShape(sqlite: BunDatabase): SchemaObjectShape {
  return new Map(
    queryAllFinalized<{ type: string; name: string; table_name: string; sql: string | null }>(
      sqlite,
      `SELECT type, name, tbl_name AS table_name, sql
       FROM sqlite_schema
       WHERE name NOT LIKE 'sqlite_%'
       ORDER BY type, name`,
    ).map((row) => [
      `${row.type}:${row.name}`,
      `${row.table_name}:${row.sql === null ? "<implicit>" : row.sql.trim()}`,
    ]),
  )
}

export function schemaObjectFingerprint(sqlite: BunDatabase): string {
  return createHash("sha256").update(JSON.stringify([...readSchemaObjectShape(sqlite)])).digest("hex")
}

function expectedSchemaObjectShape(): SchemaObjectShape {
  const sqlite = new BunDatabase(":memory:")
  try {
    sqlite.exec(SCHEMA_DDL)
    return readSchemaObjectShape(sqlite)
  } finally {
    sqlite.close(true)
  }
}

function findShapeDrift(
  expected: SchemaObjectShape,
  actual: SchemaObjectShape,
  include: (objectKey: string) => boolean = () => true,
): string | undefined {
  for (const objectKey of actual.keys()) {
    if (include(objectKey) && !expected.has(objectKey)) return `unexpected schema object ${objectKey}`
  }
  for (const [objectKey, expectedSql] of expected) {
    if (!include(objectKey)) continue
    const actualSql = actual.get(objectKey)
    if (actualSql === undefined) return `missing schema object ${objectKey}`
    if (actualSql !== expectedSql) return `schema object ${objectKey} differs from current DDL`
  }
}

export function currentSchemaFingerprint(): string {
  const sqlite = new BunDatabase(":memory:")
  try {
    sqlite.exec(SCHEMA_DDL)
    return schemaObjectFingerprint(sqlite)
  } finally {
    sqlite.close(true)
  }
}

/** Return the exact SQLite-stored definition generated by the current DDL. */
export function canonicalSchemaObjectSQL(type: "table" | "index" | "trigger", name: string): string {
  const sqlite = new BunDatabase(":memory:")
  try {
    sqlite.exec(SCHEMA_DDL)
    const statement = sqlite.query<{ sql: string | null }, [string, string]>(
      "SELECT sql FROM sqlite_schema WHERE type=? AND name=?",
    )
    try {
      const definition = statement.get(type, name)?.sql
      if (!definition) throw new Error(`Current schema is missing ${type} ${name}`)
      return definition
    } finally {
      statement.finalize()
    }
  } finally {
    sqlite.close(true)
  }
}

export function findSchemaDrift(sqlite: BunDatabase): string | undefined {
  return findShapeDrift(expectedSchemaObjectShape(), readSchemaObjectShape(sqlite))
}

export function hasApplicationSchema(sqlite: BunDatabase): boolean {
  return readSchemaObjectShape(sqlite).size > 0
}

function quoteIdentifier(name: string): string {
  return `"${name.replaceAll('"', '""')}"`
}

function readTriggerDefinitions(sqlite: BunDatabase): Map<string, string> {
  return new Map(
    queryAllFinalized<{ name: string; sql: string | null }>(
      sqlite,
      `SELECT name, sql
       FROM sqlite_schema
       WHERE type = 'trigger' AND name NOT LIKE 'sqlite_%'
       ORDER BY name`,
    ).map((row) => [row.name, row.sql === null ? "" : row.sql.trim()]),
  )
}

/** Restore triggers deliberately suspended by the strict current-schema
 * transfer while referenced rows are inserted. This is not a startup repair
 * or schema-upgrade authority: every non-trigger object must already equal the
 * current DDL, and the caller owns the enclosing transfer transaction. */
export function restoreCurrentTransferTriggers(
  sqlite: BunDatabase,
): string[] {
  const reference = new BunDatabase(":memory:")
  let expected: Map<string, string>
  let expectedShape: SchemaObjectShape
  try {
    reference.exec(SCHEMA_DDL)
    expected = readTriggerDefinitions(reference)
    expectedShape = readSchemaObjectShape(reference)
  } finally {
    reference.close(true)
  }
  const actualShape = readSchemaObjectShape(sqlite)
  if (findShapeDrift(expectedShape, actualShape, (objectKey) => !objectKey.startsWith("trigger:"))) return []
  const actual = readTriggerDefinitions(sqlite)
  const reconciled: string[] = []
  for (const [name, definition] of expected) {
    if (actual.get(name) === definition) continue
    if (actual.has(name)) sqlite.run(`DROP TRIGGER ${quoteIdentifier(name)}`)
    sqlite.exec(definition)
    reconciled.push(name)
  }
  for (const name of actual.keys()) {
    if (expected.has(name)) continue
    sqlite.run(`DROP TRIGGER ${quoteIdentifier(name)}`)
    reconciled.push(name)
  }
  return reconciled
}
