import type { AnySQLiteTable } from "drizzle-orm/sqlite-core"
import { ControlAccountTable } from "../control/control.sql"
import { DatabaseAuthorityTable } from "./database.sql"
import {
  BusPublicationAttemptReceiptTable,
  BusPublicationDeliveryReceiptTable,
  BusPublicationDeliveryTable,
  BusPublicationOutboxTable,
  BusPublicationPhaseReceiptTable,
} from "../bus/bus.sql"
import { ChannelIngressAcceptedTable, ChannelIngressOutcomeTable } from "../channel/channel.sql"
import {
  SessionTable,
  MessageTable,
  PartTable,
  ToolPartRequestTable,
  ToolPartProgressTable,
  ToolPartOutcomeTable,
  ProviderActivityRequestTable,
  ProviderActivityOutcomeTable,
  InteractiveArtifactTable,
  SessionControlRecordTable,
  SessionControlEventTable,
  SessionPromptOwnerTable,
  WorkerTurnDescriptorTable,
  TodoTable,
  TodoSnapshotTable,
} from "../session/session.sql"
import {
  PermissionExecutionResultTable,
  PermissionLedgerTable,
  PermissionPolicyTable,
} from "../permission/permission.sql"
import { SessionShareTable } from "../share/share.sql"
import { ProjectDirectoryAdmissionTable, ProjectMaintenanceFenceTable, ProjectTable } from "../project/project.sql"
import { WorkspaceTable } from "../workspace/workspace.sql"
import { MemoryFileTable, MemoryChunkTable, MemoryEmbeddingTable } from "../memory/memory.sql"
import {
  AutomationDefinitionTombstoneTable,
  AutomationProjectTargetTable,
  AutomationRunReceiptTable,
  AutomationRunTable,
  AutomationTable,
} from "../scheduler/automation.sql"
import {
  EventJobDefinitionTombstoneTable,
  EventJobFireReceiptTable,
  EventJobFireTable,
  EventJobTable,
  EventOccurrenceTable,
} from "../scheduler/event.sql"
import { TaskPlanTable } from "../memory/task-plan.sql"
import { WorkbenchBriefSnapshotTable } from "../workbench/workbench.sql"
import {
  EngineTaskTable,
  EngineTaskRootIngressPolicyTable,
  EngineTaskRootIngressTable,
  EngineControlActivationLeaseTable,
  EngineBuildObservationCleanupTable,
  EngineBuildObservationCleanupReceiptTable,
  EngineGoalTable,
  EngineInteractionRequestTable,
  EngineInteractionOutcomeTable,
  EngineArtifactTable,
  EngineWorkflowNodeOccurrenceTable,
  EngineBrowserPreviewTargetIdentityTable,
  EngineArtifactCatalogRevisionTable,
  EngineArtifactVersionTable,
  EngineProgressSnapshotTable,
  EngineGitCheckpointRequestTable,
  EngineGitCheckpointOutcomeTable,
  EngineChannelBindingTable,
} from "../engine/engine.sql"
import { ProtocolDeliveryReceiptTable, ProtocolEventTable, ProtocolInboxTable } from "../protocol/protocol.sql"
import { QuickNoteTable } from "../quicknote/quicknote.sql"
import { DecisionLogTable } from "../decision-log/schema"
import { EngineMetricSpecTable, EngineMetricResultTable } from "../metrics/metrics.sql"
import { ProviderUsageEventTable } from "../usage/usage.sql"

export {
  ControlAccountTable,
  DatabaseAuthorityTable,
  BusPublicationDeliveryTable,
  BusPublicationDeliveryReceiptTable,
  BusPublicationPhaseReceiptTable,
  BusPublicationAttemptReceiptTable,
  BusPublicationOutboxTable,
  ChannelIngressAcceptedTable,
  ChannelIngressOutcomeTable,
  SessionTable,
  MessageTable,
  PartTable,
  ToolPartRequestTable,
  ToolPartProgressTable,
  ToolPartOutcomeTable,
  ProviderActivityRequestTable,
  ProviderActivityOutcomeTable,
  InteractiveArtifactTable,
  SessionControlRecordTable,
  SessionControlEventTable,
  SessionPromptOwnerTable,
  WorkerTurnDescriptorTable,
  TodoTable,
  TodoSnapshotTable,
  PermissionExecutionResultTable,
  PermissionLedgerTable,
  PermissionPolicyTable,
  SessionShareTable,
  ProjectTable,
  ProjectMaintenanceFenceTable,
  ProjectDirectoryAdmissionTable,
  WorkspaceTable,
  MemoryFileTable,
  MemoryChunkTable,
  MemoryEmbeddingTable,
  AutomationProjectTargetTable,
  AutomationRunTable,
  AutomationRunReceiptTable,
  AutomationTable,
  AutomationDefinitionTombstoneTable,
  EventJobFireTable,
  EventJobFireReceiptTable,
  EventJobTable,
  EventJobDefinitionTombstoneTable,
  EventOccurrenceTable,
  TaskPlanTable,
  WorkbenchBriefSnapshotTable,
  EngineTaskTable,
  EngineTaskRootIngressPolicyTable,
  EngineTaskRootIngressTable,
  EngineControlActivationLeaseTable,
  EngineBuildObservationCleanupTable,
  EngineBuildObservationCleanupReceiptTable,
  EngineGoalTable,
  EngineInteractionRequestTable,
  EngineInteractionOutcomeTable,
  EngineArtifactTable,
  EngineWorkflowNodeOccurrenceTable,
  EngineBrowserPreviewTargetIdentityTable,
  EngineArtifactCatalogRevisionTable,
  EngineArtifactVersionTable,
  EngineProgressSnapshotTable,
  EngineGitCheckpointRequestTable,
  EngineGitCheckpointOutcomeTable,
  EngineChannelBindingTable,
  ProtocolEventTable,
  ProtocolInboxTable,
  ProtocolDeliveryReceiptTable,
  QuickNoteTable,
  DecisionLogTable,
  EngineMetricSpecTable,
  EngineMetricResultTable,
  ProviderUsageEventTable,
}

export const ApplicationSchema = {
  ControlAccountTable,
  DatabaseAuthorityTable,
  BusPublicationDeliveryTable,
  BusPublicationDeliveryReceiptTable,
  BusPublicationPhaseReceiptTable,
  BusPublicationAttemptReceiptTable,
  BusPublicationOutboxTable,
  ChannelIngressAcceptedTable,
  ChannelIngressOutcomeTable,
  SessionTable,
  MessageTable,
  PartTable,
  ToolPartRequestTable,
  ToolPartProgressTable,
  ToolPartOutcomeTable,
  ProviderActivityRequestTable,
  ProviderActivityOutcomeTable,
  InteractiveArtifactTable,
  SessionControlRecordTable,
  SessionControlEventTable,
  SessionPromptOwnerTable,
  WorkerTurnDescriptorTable,
  TodoTable,
  TodoSnapshotTable,
  PermissionExecutionResultTable,
  PermissionLedgerTable,
  PermissionPolicyTable,
  SessionShareTable,
  ProjectTable,
  ProjectMaintenanceFenceTable,
  ProjectDirectoryAdmissionTable,
  WorkspaceTable,
  MemoryFileTable,
  MemoryChunkTable,
  MemoryEmbeddingTable,
  AutomationProjectTargetTable,
  AutomationRunTable,
  AutomationRunReceiptTable,
  AutomationTable,
  AutomationDefinitionTombstoneTable,
  EventJobFireTable,
  EventJobFireReceiptTable,
  EventJobTable,
  EventJobDefinitionTombstoneTable,
  EventOccurrenceTable,
  TaskPlanTable,
  WorkbenchBriefSnapshotTable,
  EngineTaskTable,
  EngineTaskRootIngressPolicyTable,
  EngineTaskRootIngressTable,
  EngineControlActivationLeaseTable,
  EngineBuildObservationCleanupTable,
  EngineBuildObservationCleanupReceiptTable,
  EngineGoalTable,
  EngineInteractionRequestTable,
  EngineInteractionOutcomeTable,
  EngineArtifactTable,
  EngineWorkflowNodeOccurrenceTable,
  EngineBrowserPreviewTargetIdentityTable,
  EngineArtifactCatalogRevisionTable,
  EngineArtifactVersionTable,
  EngineProgressSnapshotTable,
  EngineGitCheckpointRequestTable,
  EngineGitCheckpointOutcomeTable,
  EngineChannelBindingTable,
  ProtocolEventTable,
  ProtocolInboxTable,
  ProtocolDeliveryReceiptTable,
  QuickNoteTable,
  DecisionLogTable,
  EngineMetricSpecTable,
  EngineMetricResultTable,
  ProviderUsageEventTable,
} as const satisfies Record<string, AnySQLiteTable>
