import { z } from "zod"

export const SourceCoverageActionSchema = z.enum(["reuse", "modify", "preserve", "replace"])
export type SourceCoverageAction = z.infer<typeof SourceCoverageActionSchema>

export const SourceCoverageEntrySchema = z.object({
  id: z.string().min(1).describe("Stable source coverage id, e.g. src-router-shell"),
  paths: z.array(z.string().min(1)).min(1).describe("Existing source paths this row covers"),
  goal_ids: z.array(z.string().min(1)).min(1).describe("Goals responsible for these paths"),
  action: SourceCoverageActionSchema.describe("How the owned source surface is treated"),
  rationale: z.string().min(5).describe("Why this source surface belongs to those goals"),
})
export type SourceCoverageEntry = z.infer<typeof SourceCoverageEntrySchema>

const RegionBoxSchema = z
  .object({
    x: z.number().int().nonnegative(),
    y: z.number().int().nonnegative(),
    width: z.number().int().positive(),
    height: z.number().int().positive(),
  })
  .strict()

const ReferenceRegionKeySchema = z
  .string()
  .min(1)
  .refine(
    (value) => {
      const [regionID, viewportID, extra] = value.split("@")
      return extra === undefined && Boolean(regionID?.trim()) && Boolean(viewportID?.trim())
    },
    {
      message: "reference region key must use region_id@viewport_id format",
    },
  )

export const ReferenceRegionBindingSchema = z
  .object({
    reference_region_key: ReferenceRegionKeySchema.describe(
      "Stable region_id@viewport_id key from the Frontend Design VisualRegionBinding manifest",
    ),
    source_reference_artifact: z
      .string()
      .min(1)
      .describe("Task-runtime relative PNG crop generated by create_visual_region_binding_package"),
    binding_manifest_artifact: z
      .string()
      .min(1)
      .optional()
      .describe("Task-runtime relative VisualRegionBinding manifest that contains this crop row"),
    source_bbox: RegionBoxSchema.optional().describe("Original full-page reference bounding box in source pixels"),
    crop_intent: z.string().min(1).optional().describe("Crop intent copied from the VisualRegionBinding row"),
  })
  .strict()
export type ReferenceRegionBinding = z.infer<typeof ReferenceRegionBindingSchema>

export const ReferenceCoverageEntrySchema = z.object({
  id: z.string().min(1).describe("Stable reference coverage id, e.g. ref-hero-shell"),
  surface: z.string().min(1).describe("Reference surface or interaction area"),
  goal_ids: z.array(z.string().min(1)).min(1).describe("Goals responsible for this reference surface"),
  visual_spec_ids: z.array(z.string().min(1)).default([]).describe("Visual spec ids covered by this row"),
  reference_regions: z
    .array(ReferenceRegionBindingSchema)
    .default([])
    .describe("Goal-bound crop regions produced from the Frontend Design VisualRegionBinding manifest"),
  expectation: z.string().min(5).describe("What must be preserved or restored from the reference"),
})
export type ReferenceCoverageEntry = z.infer<typeof ReferenceCoverageEntrySchema>

export const AssemblyOwnerEntrySchema = z.object({
  surface: z.string().min(1).describe("Shared assembly surface, e.g. app-shell, root-routing, final-deliverable"),
  goal_id: z.string().min(1).describe("Single owning goal id for the assembly surface"),
  rationale: z.string().min(5).describe("Why this goal owns final stitching for the surface"),
})
export type AssemblyOwnerEntry = z.infer<typeof AssemblyOwnerEntrySchema>

export interface ArchitectFidelityState {
  sourceCoverage: SourceCoverageEntry[]
  referenceCoverage: ReferenceCoverageEntry[]
  assemblyOwners: AssemblyOwnerEntry[]
}

export const ArchitectFidelityStateSchema = z
  .object({
    sourceCoverage: z.array(SourceCoverageEntrySchema),
    referenceCoverage: z.array(ReferenceCoverageEntrySchema),
    assemblyOwners: z.array(AssemblyOwnerEntrySchema),
  })
  .strict()

export function emptyArchitectFidelityState(): ArchitectFidelityState {
  return {
    sourceCoverage: [],
    referenceCoverage: [],
    assemblyOwners: [],
  }
}

export function filterGoalFidelityState(input: { goalID: string; fidelity: ArchitectFidelityState }) {
  return {
    sourceCoverage: input.fidelity.sourceCoverage.filter((row) => row.goal_ids.includes(input.goalID)),
    referenceCoverage: input.fidelity.referenceCoverage.filter((row) => row.goal_ids.includes(input.goalID)),
    assemblyOwners: input.fidelity.assemblyOwners,
  }
}
