// Generated by script/generate-work-artifact-qualification-matrix.ts. Do not edit.
export const GENERATED_WORK_ARTIFACT_QUALIFICATION_MATRIX = {
  "schema_version": 1,
  "profile": "office.presentation@1",
  "qualification": "office-presentation-packaged-lifecycle@1",
  "isolation_level": "adapter_inputs_only",
  "tool_schema_revision": "work-artifact-presentation@1",
  "tools": [
    {
      "id": "work_artifact_inspect",
      "schema_sha256": "cebbcf4a925a64f2231ffb234b6795aefd2405c6887f82a949b262cb42b33864"
    },
    {
      "id": "work_artifact_author",
      "schema_sha256": "371e731e97f9390b8469ffdbd748cf636e1d0fec3777328c35d4a56fce1d5e79"
    },
    {
      "id": "work_artifact_validate",
      "schema_sha256": "cebbcf4a925a64f2231ffb234b6795aefd2405c6887f82a949b262cb42b33864"
    },
    {
      "id": "work_artifact_deliver",
      "schema_sha256": "ce2da01b800da9b3eabaf210539427aa7975b2d42ff24a8aa51e06ebdac03364"
    }
  ],
  "skill": {
    "name": "work-artifacts",
    "profile_set": "work-artifacts@1",
    "resources": [
      "references/common-lifecycle.md",
      "references/office-presentation.md",
      "references/review.md",
      "references/security.md"
    ]
  },
  "runtime": {
    "id": "officecli",
    "version": "1.0.143",
    "source_commit": "fd4adab4dbe3283b62e3edcfad124dd648fa74bc",
    "lock_revision": "830c54ac60743b9ab2a7b9403a200d95093d82c24377620fa2ffc08a65a0d0f7"
  },
  "limits": {
    "inputBytes": 83886080,
    "outputBytes": 83886080,
    "pagesOrFrames": 40,
    "wallClockMs": 120000,
    "parserWallClockMs": 10000
  },
  "targets": [
    {
      "os": "win32",
      "arch": "x64",
      "package_smoke": {
        "checker": "script/check-work-artifact-profile.ts",
        "args": [
          "--profile",
          "office.presentation@1",
          "--package-root",
          "<package-root>"
        ],
        "release_result": "required"
      }
    },
    {
      "os": "darwin",
      "arch": "x64",
      "package_smoke": {
        "checker": "script/check-work-artifact-profile.ts",
        "args": [
          "--profile",
          "office.presentation@1",
          "--package-root",
          "<package-root>"
        ],
        "release_result": "required"
      }
    },
    {
      "os": "darwin",
      "arch": "arm64",
      "package_smoke": {
        "checker": "script/check-work-artifact-profile.ts",
        "args": [
          "--profile",
          "office.presentation@1",
          "--package-root",
          "<package-root>"
        ],
        "release_result": "required"
      }
    },
    {
      "os": "linux",
      "arch": "x64",
      "package_smoke": {
        "checker": "script/check-work-artifact-profile.ts",
        "args": [
          "--profile",
          "office.presentation@1",
          "--package-root",
          "<package-root>"
        ],
        "release_result": "required"
      }
    },
    {
      "os": "linux",
      "arch": "arm64",
      "package_smoke": {
        "checker": "script/check-work-artifact-profile.ts",
        "args": [
          "--profile",
          "office.presentation@1",
          "--package-root",
          "<package-root>"
        ],
        "release_result": "required"
      }
    }
  ],
  "required_evidence": [
    "skill_projection",
    "tool_schema",
    "runtime_lock",
    "target_package_manifest",
    "runtime_smoke",
    "compiled_opencorvus_typed_lifecycle",
    "canonical_validation_receipt",
    "fresh_delivery_revalidation"
  ]
} as const
