import { createHash } from "node:crypto"
import fs from "node:fs/promises"
import path from "node:path"
import z from "zod"
import { parseFrontmatter } from "../src/util/frontmatter"
import { Skill } from "../src/skill/skill"
import { createWorkArtifactTools } from "../src/tool/work-artifact"
import { WorkArtifactProfileRegistry } from "../src/work-artifact/profile-registry"
import { officeCliRuntime } from "../src/work-artifact/runtime/runtime-lock"
import { WORK_ARTIFACT_RUNTIME_LOCK } from "./work-artifact-runtime-lock"

export const WORK_ARTIFACT_QUALIFICATION_MATRIX_PATH = "src/work-artifact/qualification-matrix.generated.ts"

async function qualificationMatrix() {
  const profile = WorkArtifactProfileRegistry.require("office.presentation@1")
  const runtime = officeCliRuntime(WORK_ARTIFACT_RUNTIME_LOCK)
  const skillPath = path.resolve(import.meta.dir, "../src/skill/builtin", profile.skillName, "SKILL.md")
  const skill = Skill.parseDefinition(parseFrontmatter(await fs.readFile(skillPath, "utf8")).data, skillPath)
  const tools = await Promise.all(
    Object.values(createWorkArtifactTools()).map(async (tool) => {
      const initialized = await tool.init()
      const schema = z.toJSONSchema(initialized.parameters)
      return {
        id: tool.id,
        schema_sha256: createHash("sha256").update(JSON.stringify(schema)).digest("hex"),
      }
    }),
  )
  const targets = profile.releaseTargets.map((target) => ({
    os: target.os,
    arch: target.arch,
    package_smoke: {
      checker: "script/check-work-artifact-profile.ts",
      args: ["--profile", profile.id, "--package-root", "<package-root>"],
      release_result: "required",
    },
  }))
  return {
    schema_version: 1,
    profile: profile.id,
    qualification: "office-presentation-packaged-lifecycle@1",
    isolation_level: profile.networkIsolation,
    tool_schema_revision: profile.toolSchemaRevision,
    tools,
    skill: {
      name: skill.name,
      profile_set: skill.metadata?.["opencorvus.profile-set"],
      resources: profile.skillResources,
    },
    runtime: {
      id: runtime.id,
      version: runtime.version,
      source_commit: runtime.source.commit,
      lock_revision: createHash("sha256").update(JSON.stringify(WORK_ARTIFACT_RUNTIME_LOCK)).digest("hex"),
    },
    limits: profile.limits,
    targets,
    required_evidence: [
      "skill_projection",
      "tool_schema",
      "runtime_lock",
      "target_package_manifest",
      "runtime_smoke",
      "compiled_opencorvus_typed_lifecycle",
      "canonical_validation_receipt",
      "fresh_delivery_revalidation",
    ],
  }
}

export async function generateWorkArtifactQualificationMatrix(packageRoot = path.resolve(import.meta.dir, "..")) {
  const output = `${[
    "// Generated by script/generate-work-artifact-qualification-matrix.ts. Do not edit.",
    `export const GENERATED_WORK_ARTIFACT_QUALIFICATION_MATRIX = ${JSON.stringify(await qualificationMatrix(), undefined, 2)} as const`,
    "",
  ].join("\n")}`
  const filename = path.join(packageRoot, WORK_ARTIFACT_QUALIFICATION_MATRIX_PATH)
  if (process.argv.includes("--check")) {
    const current = await fs.readFile(filename, "utf8").catch(() => "")
    if (current !== output) throw new Error(`Generated Work Artifact qualification matrix is stale: ${filename}`)
    return filename
  }
  await fs.writeFile(filename, output)
  return filename
}

if (import.meta.main) {
  console.log(await generateWorkArtifactQualificationMatrix())
}
