import type { LucideIcon } from "lucide-solid"
import {
  Activity,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Archive,
  ArchiveRestore,
  Ban,
  Bell,
  Bot,
  BookOpenText,
  Boxes,
  BriefcaseBusiness,
  Bug,
  Cable,
  ChartNoAxesColumn,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleAlert,
  CircleCheck,
  CircleHelp,
  CircleX,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Cog,
  Compass,
  Copy,
  Cpu,
  DraftingCompass,
  Download,
  FileCheck2,
  FileText,
  Files,
  Folder,
  FolderOpen,
  FolderPlus,
  FolderSearch,
  GitBranch,
  GitCompareArrows,
  Globe,
  Hammer,
  Images,
  Inbox,
  Info,
  Layers,
  Link2,
  ListTree,
  ListTodo,
  LoaderCircle,
  LockKeyhole,
  Logs,
  MailCheck,
  Mails,
  MessageSquare,
  Map,
  Maximize2,
  MemoryStick,
  MoreHorizontal,
  MoreVertical,
  Minus,
  Network,
  OctagonX,
  Orbit,
  Package,
  PackagePlus,
  PanelLeft,
  PanelRight,
  Paperclip,
  Palette,
  PanelsTopLeft,
  Pencil,
  Pin,
  Play,
  Plus,
  Presentation,
  RefreshCw,
  Route,
  Rss,
  Search,
  SearchCheck,
  ScanEye,
  ScanSearch,
  ScrollText,
  Send,
  Settings,
  Shell,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  Sun,
  Square,
  SquareTerminal,
  Store,
  Terminal,
  Telescope,
  Target,
  Trash2,
  Undo2,
  Upload,
  Wrench,
  Workflow,
  X,
  UserRound,
  UsersRound,
  ZoomIn,
  ZoomOut,
} from "lucide-solid"

export interface LucideIconRecord {
  component: LucideIcon
  strokeWidth?: number
  class?: string
}

export const LUCIDE_ICON_MAP = {
  close: { component: X },
  chevron: { component: ChevronRight },
  "chevron-up": { component: ChevronUp },
  "chevron-down": { component: ChevronDown },
  "nav-back": { component: ArrowLeft },
  "nav-forward": { component: ArrowRight },
  plus: { component: Plus },
  "zoom-in": { component: ZoomIn },
  "zoom-out": { component: ZoomOut },
  "arrow-up": { component: ArrowUp, strokeWidth: 2 },
  minimize: { component: Minus, strokeWidth: 2.1 },
  maximize: { component: Maximize2, strokeWidth: 1.8 },
  restore: { component: PanelsTopLeft, strokeWidth: 1.7 },
  "panel-left": { component: PanelLeft },
  "panel-right": { component: PanelRight },
  terminal: { component: Terminal },
  tasks: { component: ListTodo },
  message: { component: MessageSquare },
  work: { component: BriefcaseBusiness },
  "more-horizontal": { component: MoreHorizontal },
  "more-vertical": { component: MoreVertical },
  notifications: { component: Bell },
  mailbox: { component: Mails },
  scheduled: { component: Clock },
  run: { component: Play },
  "mail-check": { component: MailCheck },
  inbox: { component: Inbox },
  screenshots: { component: Images },
  "terminal-powershell": { component: SquareTerminal },
  "terminal-bash": { component: Shell },
  folder: { component: Folder },
  "folder-open": { component: FolderOpen },
  "project-add": { component: FolderPlus },
  "git-branch": { component: GitBranch },
  "git-compare": { component: GitCompareArrows },
  "runtime-environment": { component: SlidersHorizontal },
  attach: { component: Paperclip },
  "web-search": { component: Globe },
  "expert-squad-catalog": { component: Boxes },
  "expert-squad": { component: UsersRound },
  send: { component: Send },
  stop: { component: Square },
  copy: { component: Copy },
  check: { component: Check },
  inspect: { component: ScanSearch },
  bug: { component: Bug },
  cancel: { component: OctagonX },
  edit: { component: Pencil },
  rewind: { component: Undo2 },
  search: { component: Search },
  refresh: { component: RefreshCw },
  loading: { component: LoaderCircle, strokeWidth: 1.8 },
  "file-document": { component: FileText },
  presentation: { component: Presentation },
  "info-circle": { component: Info },
  "model-metadata": { component: Cpu },
  "usage-metrics": { component: ChartNoAxesColumn },
  "interaction-question": { component: CircleHelp },
  "interaction-permission": { component: LockKeyhole },
  "log-lines": { component: Logs },
  download: { component: Download },
  pin: { component: Pin, class: "oc-icon-pin" },
  upload: { component: Upload },
  archive: { component: Archive },
  "archive-restore": { component: ArchiveRestore },
  delete: { component: Trash2 },
  "status-idle": { component: Circle },
  "status-queued": { component: Clock },
  "status-active": { component: Activity },
  "status-completed": { component: CircleCheck },
  "status-failed": { component: CircleX },
  "status-cancelled": { component: Ban },
  "error-reason": { component: CircleAlert },
  "avatar-user": { component: UserRound },
  "avatar-assistant": { component: Sparkles },
  "avatar-system": { component: Cog },
  "avatar-orchestrator": { component: Orbit },
  "avatar-intent-analysis": { component: SearchCheck },
  "avatar-spec": { component: BookOpenText },
  "avatar-requirements": { component: ClipboardList },
  "avatar-frontend-design": { component: Palette },
  "avatar-frontend-research": { component: FolderSearch },
  "avatar-visual-qa": { component: ScanEye },
  "avatar-architect": { component: DraftingCompass },
  "avatar-goal-workload-analyst": { component: ChartNoAxesColumn },
  "avatar-planner": { component: Map },
  "avatar-build": { component: Hammer },
  "avatar-explore": { component: Compass },
  "avatar-deep-research": { component: Telescope },
  "avatar-integrity": { component: ShieldCheck },
  "avatar-fact-check": { component: FileCheck2 },
  spec: { component: ScrollText },
  plan: { component: Route },
  goals: { component: Target },
  executor: { component: Play },
  acceptance: { component: ClipboardCheck },
  files: { component: Files },
  mission: { component: Sparkles },
  "channel-link": { component: Link2 },
  "config-general": { component: Settings },
  "config-appearance": { component: Sun },
  "config-channel": { component: Rss },
  "config-expert-squad-install": { component: PackagePlus },
  "config-expert-squad-details": { component: ListTree },
  "config-tool": { component: Wrench },
  "config-skill": { component: Package },
  "config-skill-market": { component: Store },
  "config-mcp": { component: Cable },
  "config-memory": { component: MemoryStick },
  "config-network": { component: Network },
  "config-providers": { component: Layers },
  "config-agent-models": { component: Bot },
  workflow: { component: Workflow },
} as const satisfies Record<string, LucideIconRecord>

export type LucideIconName = keyof typeof LUCIDE_ICON_MAP
