import { writeFile } from "node:fs/promises"
import { ExpertSquadPackageManager } from "../../opencorvus/src/expert-squad/manager"
import { ExpertSquadRegistry } from "../../opencorvus/src/expert-squad/registry"
import { payloadPackageSources } from "../../opencorvus/generated/expert-squad-payload"
import { projectExpertSquadFacts } from "../src/lib/expert-squad-facts"

const selectedIdentities = [
  "builtin/frontend-replica",
  "builtin/frontend-innovate",
  "builtin/deep-research",
  "builtin/equity-research",
  "builtin/review-debug",
] as const

const market = await ExpertSquadPackageManager.payloadMarket({ projectDirectory: process.cwd() })
const marketByIdentity = new Map(market.map((item) => [`${item.namespace}/${item.id}`, item]))
const sourceByIdentity = new Map(payloadPackageSources.map((source) => [`${source.namespace}/${source.id}`, source]))

const facts = selectedIdentities.map((identity) => {
  const item = marketByIdentity.get(identity)
  const source = sourceByIdentity.get(identity)
  if (!item || !source) throw new Error(`Public market selection is not an exact payload package: ${identity}`)

  const loaded = ExpertSquadRegistry.loadEmbeddedPackageDeclaration(source)
  if (item.packageDigest !== loaded.packageDigest) {
    throw new Error(`Payload market and embedded declaration disagree for ${identity}`)
  }
  return projectExpertSquadFacts(loaded)
})

const output = [
  "// Auto-generated by script/generate-public-market.ts from ExpertSquadPackageManager.payloadMarket().",
  "// Do not edit factual identity, revision, projection, capability, or workflow data here.",
  `export const generatedPublicMarketFacts = ${JSON.stringify(facts, null, 2)} as const`,
  "",
].join("\n")

await writeFile(new URL("../src/content/public-market-facts.generated.ts", import.meta.url), output)
