import path from "node:path"
import { fileURLToPath } from "node:url"
import { writeFile } from "node:fs/promises"
import { ExpertSquadPackageManager } from "../../opencorvus/src/expert-squad/manager"
import { ExpertSquadRegistry } from "../../opencorvus/src/expert-squad/registry"
import { EMBEDDED_EXPERT_SQUAD_IDS } from "../../opencorvus/src/expert-squad/builtin/ids"
import { payloadPackageSources } from "../../opencorvus/generated/expert-squad-payload"
import { projectExpertSquadFacts } from "../src/lib/expert-squad-facts"

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../..")

function indexedPackageSource(id: string): ExpertSquadRegistry.EmbeddedPackageSource {
  const root =
    id === "squad-sdk"
      ? `expert-squads/builtin/${id}`
      : `packages/opencorvus/src/expert-squad/builtin/${id}`
  const listed = Bun.spawnSync({
    cmd: ["git", "ls-files", "--cached", "-z", "--", root],
    cwd: repoRoot,
    stdout: "pipe",
    stderr: "pipe",
  })
  if (listed.exitCode !== 0) {
    throw new Error(`Could not read indexed embedded package ${id}: ${new TextDecoder().decode(listed.stderr)}`)
  }
  const trackedPaths = new TextDecoder()
    .decode(listed.stdout)
    .split("\0")
    .filter(Boolean)
    .sort()
  const files: Record<string, string> = {}
  for (const trackedPath of trackedPaths) {
    const shown = Bun.spawnSync({
      cmd: ["git", "show", `:${trackedPath}`],
      cwd: repoRoot,
      stdout: "pipe",
      stderr: "pipe",
    })
    if (shown.exitCode !== 0) {
      throw new Error(`Could not read indexed embedded package file ${trackedPath}: ${new TextDecoder().decode(shown.stderr)}`)
    }
    files[trackedPath.slice(root.length + 1)] = new TextDecoder("utf-8", { fatal: true }).decode(shown.stdout)
  }
  return { namespace: "builtin", id, files }
}

const selectedIdentities = [
  "builtin/frontend-replica",
  "builtin/frontend-innovate",
  "builtin/deep-research",
  "builtin/equity-research",
  "builtin/review-debug",
] as const

const market = await ExpertSquadPackageManager.payloadMarket({ projectDirectory: process.cwd() })
const marketByIdentity = new Map(market.map((item) => [`${item.namespace}/${item.id}`, item]))
const sourceByIdentity = new Map(payloadPackageSources.map((source) => [`${source.namespace}/${source.id}`, source]))

const facts = selectedIdentities.map((identity) => {
  const item = marketByIdentity.get(identity)
  const source = sourceByIdentity.get(identity)
  if (!item || !source) throw new Error(`Public market selection is not an exact payload package: ${identity}`)

  const loaded = ExpertSquadRegistry.loadEmbeddedPackageDeclaration(source)
  if (item.packageDigest !== loaded.packageDigest) {
    throw new Error(`Payload market and embedded declaration disagree for ${identity}`)
  }
  return projectExpertSquadFacts(loaded)
})

const embeddedSources = EMBEDDED_EXPERT_SQUAD_IDS.map(indexedPackageSource)
const embeddedIDs = new Set(embeddedSources.map((source) => `${source.namespace}/${source.id}`))
const shippedSources = [...embeddedSources, ...payloadPackageSources]
const shippedIdentities = shippedSources.map((source) => `${source.namespace}/${source.id}`)
if (new Set(shippedIdentities).size !== shippedIdentities.length) {
  throw new Error("Shipped Expert Squad sources must have unique namespace/id identities.")
}

const shippedFacts = shippedSources
  .map((source) => {
    const loaded = ExpertSquadRegistry.loadEmbeddedPackageDeclaration(source)
    const projections = [
      loaded.manifest.capability_projection.scheduler,
      ...Object.values(loaded.manifest.capability_projection.agents),
    ]
    const packageSkillRefs = [...new Set(projections.flatMap((projection) => projection.package_skill_refs))].sort()
    const packageSkillPaths = Object.keys(source.files)
      .filter((path) => /^skills\/[^/]+\/SKILL\.md$/.test(path))
      .sort()
    return {
      identity: loaded.namespace + "/" + loaded.id,
      namespace: loaded.namespace,
      id: loaded.id,
      label: loaded.label,
      version: loaded.version,
      packageDigest: loaded.packageDigest,
      installSurface: embeddedIDs.has(`${loaded.namespace}/${loaded.id}`) ? "embedded" : "bundled_market",
      packageSkillPaths,
      packageSkillRefs,
      agentCount: Object.keys(loaded.manifest.capability_projection.agents).length,
      workflowCount: Object.keys(loaded.manifest.capability_projection.virtual_workflows).length,
    }
  })
  .sort((left, right) => left.identity.localeCompare(right.identity))

const output = [
  "// Auto-generated by script/generate-public-market.ts from ExpertSquadPackageManager.payloadMarket().",
  "// Do not edit factual identity, revision, projection, capability, or workflow data here.",
  `export const generatedPublicMarketFacts = ${JSON.stringify(facts, null, 2)} as const`,
  "",
  `export const generatedShippedSquadFacts = ${JSON.stringify(shippedFacts, null, 2)} as const`,
  "",
].join("\n")

await writeFile(new URL("../src/content/public-market-facts.generated.ts", import.meta.url), output)
