export const LSP_BUILTIN_SERVER_ID = {
  deno: "deno",
  typescript: "typescript",
  vue: "vue",
  eslint: "eslint",
  oxlint: "oxlint",
  biome: "biome",
  gopls: "gopls",
  rubyLsp: "ruby-lsp",
  ty: "ty",
  pyright: "pyright",
  elixirLs: "elixir-ls",
  zls: "zls",
  csharp: "csharp",
  fsharp: "fsharp",
  sourcekitLsp: "sourcekit-lsp",
  rust: "rust",
  clangd: "clangd",
  svelte: "svelte",
  astro: "astro",
  jdtls: "jdtls",
  kotlinLs: "kotlin-ls",
  yamlLs: "yaml-ls",
  luaLs: "lua-ls",
  phpIntelephense: "php intelephense",
  prisma: "prisma",
  dart: "dart",
  ocamlLsp: "ocaml-lsp",
  bash: "bash",
  terraform: "terraform",
  texlab: "texlab",
  dockerfile: "dockerfile",
  gleam: "gleam",
  clojureLsp: "clojure-lsp",
  nixd: "nixd",
  tinymist: "tinymist",
  haskellLanguageServer: "haskell-language-server",
  julials: "julials",
} as const

export const LSP_BUILTIN_SERVER_IDS = new Set<string>(Object.values(LSP_BUILTIN_SERVER_ID))
