import {Database} from 'bun:sqlite';import fs from 'node:fs';
const db=new Database('C:/Users/hengu/.codex/opencorvus-product-iteration/2026-10-08/multiple-sources-live-109-01/runtime/data/opencorvus.db',{readonly:true});db.exec('BEGIN');
const taskID='tsk_g00VXOBi8f00PNKt2D7j';const task=db.query('SELECT id,project_id,session_id,request_id,request FROM engine_task WHERE id=?').get(taskID);
const ss=db.query('WITH RECURSIVE t(id) AS (SELECT session_id FROM engine_task WHERE id=? UNION ALL SELECT s.id FROM session s JOIN t ON s.parent_id=t.id) SELECT s.id,s.parent_id,s.kind FROM session s JOIN t ON s.id=t.id').all(taskID);const ids=ss.map(x=>x.id),p=ids.map(()=>'?').join(',');
const messages=db.query(`SELECT id,session_id,data FROM message WHERE session_id IN (${p}) ORDER BY time_created,id`).all(...ids).map(x=>({...x,data:JSON.parse(x.data)}));
const parts=db.query(`SELECT p.id,p.message_id,p.data FROM part p JOIN message m ON m.id=p.message_id WHERE m.session_id IN (${p}) ORDER BY p.time_created,p.id`).all(...ids).map(x=>({...x,data:JSON.parse(x.data)})).filter(x=>x.data.type==='text');
const tools=db.query(`SELECT r.id,r.message_id,r.data,o.data outcome_data FROM tool_part_request r JOIN message m ON m.id=r.message_id LEFT JOIN tool_part_outcome o ON o.request_part_id=r.id WHERE m.session_id IN (${p}) ORDER BY r.time_created,r.id`).all(...ids).map(x=>({...x,data:JSON.parse(x.data),outcome_data:x.outcome_data?JSON.parse(x.outcome_data):null}));
for(const x of tools){const a=x.outcome_data?.resultAttemptID;if(a){const r=db.query('SELECT result FROM permission_execution_result WHERE attempt_id=?').get(a);x.result=r?JSON.parse(r.result).value:null}}
const schema=db.query("PRAGMA table_info(engine_artifact)").all();
const facts={task,sessions:ss,messages,parts,tools:tools.filter(x=>['manage_task','webfetch','read_agent_message'].includes(x.data.tool)),artifactSchema:schema};db.exec('ROLLBACK');db.close();fs.writeFileSync('.tmp-product-iteration/final-answer-111-facts.json',JSON.stringify(facts,null,2),{flag:'wx'});console.log(JSON.stringify({messages:messages.map(x=>({id:x.id,session:x.session_id,role:x.data.role,finish:x.data.finish})),texts:parts.map(x=>({id:x.id,message:x.message_id,text:x.data.text})),manage:tools.filter(x=>x.data.tool==='manage_task'),artifactSchema:schema},null,2));
