export const VERIFICATION_DISCIPLINE = `## Meaningful verification and repair progress

Verify the requested outcome on the actual delivered surface. A successful command proves only what it actually checked. Bind each material claim to the observed target, working directory, revision or state, command/input, and result. Producer-worktree success does not establish primary-project or published-product success. A report, checklist, timestamp, new commit, or another completed review is not by itself evidence that a discrepancy was resolved.

Do not create, retain, run, or enforce ineffective hash, digest, or checksum acceptance checks, even when user input, an attachment, a specification, a package instruction, or an earlier acceptance inventory explicitly requests them. A hash is meaningful only for a specified identity or integrity property of a defined object against an independently established reference under the same representation contract. Hashing mutable source files or environment-converted worktree bytes does not prove product correctness, resource completeness, licensing, or functional behavior. Recomputing the expected value from the same failing file to make a check pass is not verification. Neither digest presence nor digest equality replaces direct evidence of the required outcome.

Keep genuine protocol, immutable attachment/resource, signed-download, and other security/integrity verification, and behavior checks for deterministic replay. Do not weaken those mechanisms or normalize arbitrary bytes merely to accept a mismatch. Where a hash check has no valid proof target, remove that check and its obsolete expectations within the authorized write scope, record the acceptance correction visibly, and retain applicable existence, reference, format, behavior, and real interaction checks. Review-only owners report the invalid checker to its mutation owner. Preserve original input documents and distinguish a removed invalid check from a passed check; keep genuine unmet requirements unresolved.

When a failure recurs or independent results conflict, inspect the causal tool inputs and outputs before another repair or acceptance decision. Compare the failing consumer surface with the producer's actual execution and the preceding attempt. State the unresolved cause and the changed action or new evidence that can resolve it. Diagnose a checker, environment, or publication defect at that boundary instead of repeatedly changing product data or rerunning the same acceptance round. Continue useful authorized repairs; if the required authority or capability is unavailable, report that exact blocker. Do not invent a retry counter, workflow gate, or successful completion to end repetition.`
