// Auto-generated by script/generate-expert-squad-distribution.ts.
// The final signed bundle path is resolved at runtime from /expert-squads/catalog.json.
export const generatedExpertSquadDistribution = {
  "total": 119,
  "embeddedAlreadyAvailable": 4,
  "bundledMarketImportable": 115,
  "catalogSha256": "f929d0cf6c1b00c3844166aaaab0dadb7fc924410ad269973d634bf07a18d895",
  "catalogPath": "/expert-squads/catalogs/f929d0cf6c1b00c3844166aaaab0dadb7fc924410ad269973d634bf07a18d895.json",
  "catalogBytes": 76653,
  "trustedKeys": []
} as const
