// Auto-generated by script/generate-expert-squad-distribution.ts.
// The final signed bundle path is resolved at runtime from /expert-squads/catalog.json.
export const generatedExpertSquadDistribution = {
  "total": 119,
  "embeddedAlreadyAvailable": 4,
  "bundledMarketImportable": 115,
  "catalogSha256": "a2ad942bbd270226b174d8d775b2442cee14cb75d7ef42a034b1e1196b563bd6",
  "catalogPath": "/expert-squads/catalogs/a2ad942bbd270226b174d8d775b2442cee14cb75d7ef42a034b1e1196b563bd6.json",
  "catalogBytes": 76655,
  "trustedKeys": []
} as const
