// Auto-generated by script/generate-expert-squad-distribution.ts.
// The final signed bundle path is resolved at runtime from /expert-squads/catalog.json.
export const generatedExpertSquadDistribution = {
  "total": 119,
  "embeddedAlreadyAvailable": 4,
  "bundledMarketImportable": 115,
  "catalogSha256": "6ba15fbc8e760c10f0be18d61189884322c0e300b134cb45e77c6fea7e07ae70",
  "catalogPath": "/expert-squads/catalogs/6ba15fbc8e760c10f0be18d61189884322c0e300b134cb45e77c6fea7e07ae70.json",
  "catalogBytes": 76653,
  "trustedKeys": []
} as const
