// Auto-generated by script/generate-public-market.ts. Do not edit.
// Consumed by the statically prerendered landing page, which cannot import the bun:sqlite registry.

export const generatedFeaturedSquads = [
  {
    "identity": {
      "namespace": "builtin",
      "id": "advanced",
      "version": "2026.08.13.1",
      "digest": "7fb196749dc865676b15a451be2c2ad444ed8dd16e88c3b2ee092f4708bf2f4e"
    },
    "displayLabel": {
      "root": "Advanced",
      "zh-cn": "Advanced"
    },
    "description": {
      "root": "Built-in advanced software delivery team with retained Requirements-to-Architect traceability and parallel investigation, implementation, testing, interface, and independent-review frontiers.",
      "zh-cn": "内置的高级软件交付团队，保留从需求到架构的可追溯性，以及并行调查、实施、测试、界面与独立审查边界。"
    },
    "pillars": [
      "code",
      "work"
    ],
    "agentCount": 14,
    "workflowCount": 5
  },
  {
    "identity": {
      "namespace": "builtin",
      "id": "evolution-lab",
      "version": "2026.08.19.1",
      "digest": "294cd20d06abbedb81ce87949cfc59459106559ceee5f363f92de34ff63ef93e"
    },
    "displayLabel": {
      "root": "Evolution Lab",
      "zh-cn": "演进实验室"
    },
    "description": {
      "root": "Target-agnostic evidence, candidate, evaluation, integrity review, and recommendation package for explicit Expert Squad evolution campaigns.",
      "zh-cn": "为明确的 Expert Squad 演进活动提供不依赖具体目标类型的证据、候选方案、评估、完整性审查和建议资料包。"
    },
    "pillars": [
      "code",
      "work"
    ],
    "agentCount": 7,
    "workflowCount": 3
  },
  {
    "identity": {
      "namespace": "builtin",
      "id": "frontend-innovate",
      "version": "2026.08.13.1",
      "digest": "4466ac0cbef31b7c13d018d837d7fd26bab4d8b0c16a280ce99305c00b929245"
    },
    "displayLabel": {
      "root": "Frontend Innovate",
      "zh-cn": "前端创新"
    },
    "description": {
      "root": "Evidence-backed product redesign, visual direction, implementation, and rendered proof through durable catalog facts and visible narrative Turn summaries.",
      "zh-cn": "通过持久的目录事实和可见的叙事式 Turn 摘要，开展有证据支持的产品重设计、视觉方向制定、实现与渲染证明。"
    },
    "pillars": [
      "code"
    ],
    "agentCount": 9,
    "workflowCount": 1
  },
  {
    "identity": {
      "namespace": "builtin",
      "id": "academic-paper-review",
      "version": "2026.08.13.1",
      "digest": "c2bdbec244e687adf67a1c03e425d4408605b9a069a51d489948c6f95ded805c"
    },
    "displayLabel": {
      "root": "Academic Paper Review",
      "zh-cn": "学术论文审查"
    },
    "description": {
      "root": "Evidence-traceable manuscript review across literature, novelty, logic, methods, facts, citations, hallucination risk, presentation, and integrated revision guidance.",
      "zh-cn": "对手稿进行证据可追溯的审查，覆盖文献、新颖性、逻辑、方法、事实、引文、幻觉风险与呈现方式，并汇总为 revision 指南。"
    },
    "pillars": [
      "work"
    ],
    "agentCount": 8,
    "workflowCount": 1
  },
  {
    "identity": {
      "namespace": "builtin",
      "id": "frontend-replica",
      "version": "2026.08.13.1",
      "digest": "3be05221a063acf5d7f9882a1a06abf94444b49dda1f43eb2b18d846e57036a6"
    },
    "displayLabel": {
      "root": "Frontend Replica",
      "zh-cn": "前端复刻"
    },
    "description": {
      "root": "Source URL and reference-screenshot replica with a desktop surface ledger, rendered proof, durable catalog facts, and visible narrative Turn summaries.",
      "zh-cn": "基于源 URL 和参考截图完成复刻，提供桌面端界面清单、渲染证明、持久的目录事实和可见的叙事式 Turn 摘要。"
    },
    "pillars": [
      "code"
    ],
    "agentCount": 7,
    "workflowCount": 2
  },
  {
    "identity": {
      "namespace": "builtin",
      "id": "omnichannel-distribution",
      "version": "2026.08.19.1",
      "digest": "d47aa7e9bbdbd6ae0d3259f30bdcd61c0c20147543e86e5fe5a834f83b9bb8e2"
    },
    "displayLabel": {
      "root": "Omnichannel Distribution",
      "zh-cn": "全渠道分发"
    },
    "description": {
      "root": "Current channel research, rights-aware adaptation, measurement planning, readiness review, and canonical prepared-not-posted delivery bundles.",
      "zh-cn": "开展当前渠道研究、考虑权利的适配、衡量规划、准备度审查，并形成规范的已准备但未发布交付包。"
    },
    "pillars": [
      "work"
    ],
    "agentCount": 8,
    "workflowCount": 1
  }
] as const
