// Auto-generated by script/generate-public-market.ts. Do not edit.
// Consumed by the statically prerendered landing page, which cannot import the bun:sqlite registry.

export const generatedFeaturedSquads = [
  {
    "identity": {
      "namespace": "builtin",
      "id": "advanced",
      "version": "2026.09.12.1",
      "digest": "d282f09aeede890d88fe945ade39249225d0932ffac795fdeb01ebe14c85948c"
    },
    "displayLabel": {
      "root": "Advanced",
      "zh-cn": "Advanced"
    },
    "description": {
      "root": "Built-in advanced software delivery team with capability-matched Requirements-to-Architect traceability, execution, testing, interface, and independent-review frontiers.",
      "zh-cn": "内置的高级软件交付团队，保留能力匹配的需求到架构可追溯性，以及执行、测试、界面与独立审查边界。"
    },
    "pillars": [
      "code",
      "work"
    ],
    "agentCount": 14,
    "workflowCount": 6
  },
  {
    "identity": {
      "namespace": "builtin",
      "id": "evolution-lab",
      "version": "2026.09.06.1",
      "digest": "46be60cd24ec9a476e157275f540dfe3536a5744c86139a8387864c689a55a8c"
    },
    "displayLabel": {
      "root": "Evolution Lab",
      "zh-cn": "演进实验室"
    },
    "description": {
      "root": "Target-agnostic evidence, candidate, evaluation, integrity review, and recommendation package for explicit Expert Squad evolution campaigns.",
      "zh-cn": "为明确的 Expert Squad 演进活动提供不依赖具体目标类型的证据、候选方案、评估、完整性审查和建议资料包。"
    },
    "pillars": [
      "code",
      "work"
    ],
    "agentCount": 7,
    "workflowCount": 3
  },
  {
    "identity": {
      "namespace": "builtin",
      "id": "frontend-innovate",
      "version": "2026.08.30.2",
      "digest": "b5a0273ecd137e3df5c8a17a053b0a038e781d00e2661aef2318b67643b3bbe6"
    },
    "displayLabel": {
      "root": "Frontend Innovate",
      "zh-cn": "前端创新"
    },
    "description": {
      "root": "Evidence-backed product redesign, visual direction, implementation, and rendered proof through durable catalog facts and visible narrative Turn summaries.",
      "zh-cn": "通过持久的目录事实和可见的叙事式 Turn 摘要，开展有证据支持的产品重设计、视觉方向制定、实现与渲染证明。"
    },
    "pillars": [
      "code"
    ],
    "agentCount": 9,
    "workflowCount": 1
  },
  {
    "identity": {
      "namespace": "builtin",
      "id": "academic-paper-review",
      "version": "2026.08.30.2",
      "digest": "48eecad837a7720cf1988e4b1b1799fb82fd2bd04927621414c436b85a488ab3"
    },
    "displayLabel": {
      "root": "Academic Paper Review",
      "zh-cn": "学术论文审查"
    },
    "description": {
      "root": "Evidence-traceable manuscript review across literature, novelty, logic, methods, facts, citations, hallucination risk, presentation, and integrated revision guidance.",
      "zh-cn": "对手稿进行证据可追溯的审查，覆盖文献、新颖性、逻辑、方法、事实、引文、幻觉风险与呈现方式，并汇总为 revision 指南。"
    },
    "pillars": [
      "work"
    ],
    "agentCount": 8,
    "workflowCount": 1
  },
  {
    "identity": {
      "namespace": "builtin",
      "id": "frontend-replica",
      "version": "2026.08.30.2",
      "digest": "d267dd5904ca041bb60d12a1e97795a99d4a67e983ec2d4fbc5708537dfd9e5d"
    },
    "displayLabel": {
      "root": "Frontend Replica",
      "zh-cn": "前端复刻"
    },
    "description": {
      "root": "Source URL and reference-screenshot replica with a desktop surface ledger, rendered proof, durable catalog facts, and visible narrative Turn summaries.",
      "zh-cn": "基于源 URL 和参考截图完成复刻，提供桌面端界面清单、渲染证明、持久的目录事实和可见的叙事式 Turn 摘要。"
    },
    "pillars": [
      "code"
    ],
    "agentCount": 7,
    "workflowCount": 2
  },
  {
    "identity": {
      "namespace": "builtin",
      "id": "omnichannel-distribution",
      "version": "2026.08.30.2",
      "digest": "5c2e3a4153f2ac1f61620c95d358eb0b9e016da42b115f1781f7415612864112"
    },
    "displayLabel": {
      "root": "Omnichannel Distribution",
      "zh-cn": "全渠道分发"
    },
    "description": {
      "root": "Current channel research, rights-aware adaptation, measurement planning, readiness review, and canonical prepared-not-posted delivery bundles.",
      "zh-cn": "开展当前渠道研究、考虑权利的适配、衡量规划、准备度审查，并形成规范的已准备但未发布交付包。"
    },
    "pillars": [
      "work"
    ],
    "agentCount": 8,
    "workflowCount": 1
  }
] as const
