// Auto-generated by script/generate-platform-facts.ts. Do not edit by hand.
//
// Derivations, so a reviewer can re-check every number:
//   modelProviders      Object.keys(src/provider/models-bootstrap.json).length
//   models              sum of Object.keys(provider.models).length across that catalog
//   chatChannels        READY_CHANNELS.length      (channel-runtime/src/registry.ts)
//   plannedChatChannels PLANNED_CHANNELS.length    (same file; not advertised as working)
//   builtInTools        GLOBAL_TOOL_IDS minus the experimental batch tool
export const generatedPlatformFacts = {
  "modelProviders": 87,
  "models": 2579,
  "chatChannels": 13,
  "plannedChatChannels": 14,
  "builtInTools": 42
} as const
