// Auto-generated by script/generate-public-market.ts from ExpertSquadPackageManager.payloadMarket().
// Do not edit factual identity, revision, projection, capability, or workflow data here.
export const generatedPublicMarketFacts = [
  {
    "identity": {
      "namespace": "builtin",
      "id": "frontend-replica",
      "version": "2026.08.07.1",
      "digest": "e4ca4ad50570acc15dd2041d14e4766342e6b93ec17d7539f706be666a76ba5a"
    },
    "name": "Frontend Replica",
    "label": "Frontend Replica",
    "description": "Source URL and reference-screenshot replica with a desktop surface ledger, rendered proof, durable catalog facts, and visible narrative Turn summaries.",
    "selectorSummary": "Use for source URL or reference-screenshot desktop replica work with evidence-backed parity.",
    "pillars": [
      "code"
    ],
    "agents": [
      {
        "id": "frontend-replica-explorer",
        "label": "Frontend Replica Explorer",
        "description": "Locates target implementation surfaces, assets, primitives, and integration constraints.",
        "baseRole": "explore"
      },
      {
        "id": "frontend-replica-intent-analyst",
        "label": "Frontend Replica Intent Analyst",
        "description": "Classifies source, target, desktop scope, evidence gaps, and parity obligations.",
        "baseRole": "intent-analysis"
      },
      {
        "id": "frontend-replica-requirements-analyst",
        "label": "Frontend Replica Requirements Analyst",
        "description": "Defines source-bound surface, interaction, content, asset, and rendered-parity requirements.",
        "baseRole": "requirements"
      },
      {
        "id": "frontend-replica-solution-architect",
        "label": "Frontend Replica Solution Architect",
        "description": "Maps source evidence to target components, contracts, and verification regions.",
        "baseRole": "architect"
      },
      {
        "id": "frontend-replica-interface-modeler",
        "label": "Frontend Replica Interface Modeler",
        "description": "Generates the sole task-scoped source-bound interface model and implementation contract.",
        "baseRole": "frontend-design"
      },
      {
        "id": "frontend-replica-source-researcher",
        "label": "Frontend Replica Source Researcher",
        "description": "Captures source-page structure, state, content, interaction, and screenshot evidence.",
        "baseRole": "frontend-research"
      },
      {
        "id": "frontend-replica-workload-analyst",
        "label": "Frontend Replica Workload Analyst",
        "description": "Sizes source evidence, surface implementation, interaction, and visual verification work.",
        "baseRole": "goal-workload-analyst"
      },
      {
        "id": "frontend-replica-implementer",
        "label": "Frontend Replica Implementer",
        "description": "Implements the same source-bound surface in the target project.",
        "baseRole": "build"
      },
      {
        "id": "frontend-replica-visual-reviewer",
        "label": "Frontend Replica Visual Reviewer",
        "description": "Compares rendered target evidence against source regions and interaction states.",
        "baseRole": "visual-qa"
      },
      {
        "id": "frontend-replica-integrity-reviewer",
        "label": "Frontend Replica Integrity Reviewer",
        "description": "Rejects missing regions, broken interactions, unsupported variance, and weak evidence.",
        "baseRole": "integrity"
      }
    ],
    "workflows": [
      {
        "id": "interface-modeling",
        "label": "Explicit Interface Modeling",
        "description": "Focused interface-modeling collaboration using the same unique source-project generator owner as source-replica delivery.",
        "nodes": [
          {
            "id": "frontend-replica-intent-analyst",
            "agentID": "frontend-replica-intent-analyst",
            "description": "Classifies source, target, desktop scope, evidence gaps, and parity obligations.",
            "dependsOn": []
          },
          {
            "id": "frontend-replica-source-researcher",
            "agentID": "frontend-replica-source-researcher",
            "description": "Captures source-page structure, state, content, interaction, and screenshot evidence.",
            "dependsOn": []
          },
          {
            "id": "frontend-replica-requirements-analyst",
            "agentID": "frontend-replica-requirements-analyst",
            "description": "Defines source-bound surface, interaction, content, asset, and rendered-parity requirements.",
            "dependsOn": [
              "frontend-replica-intent-analyst",
              "frontend-replica-source-researcher"
            ]
          },
          {
            "id": "frontend-replica-solution-architect",
            "agentID": "frontend-replica-solution-architect",
            "description": "Maps source evidence to target components, contracts, and verification regions.",
            "dependsOn": [
              "frontend-replica-requirements-analyst"
            ]
          },
          {
            "id": "frontend-replica-interface-modeler",
            "agentID": "frontend-replica-interface-modeler",
            "description": "Generates the sole source-bound project model and implementation contract consumed by Delivery Slice subjects.",
            "dependsOn": [
              "frontend-replica-solution-architect"
            ]
          }
        ]
      },
      {
        "id": "source-replica",
        "label": "Source Replica Delivery",
        "description": "Desktop source-replica collaboration whose nodes run once per Task from source evidence through Delivery Slice revision subjects and independent rendered review.",
        "nodes": [
          {
            "id": "frontend-replica-explorer",
            "agentID": "frontend-replica-explorer",
            "description": "Locates target implementation surfaces, assets, primitives, and integration constraints.",
            "dependsOn": []
          },
          {
            "id": "frontend-replica-intent-analyst",
            "agentID": "frontend-replica-intent-analyst",
            "description": "Classifies source, target, desktop scope, evidence gaps, and parity obligations.",
            "dependsOn": [
              "frontend-replica-source-researcher"
            ]
          },
          {
            "id": "frontend-replica-source-researcher",
            "agentID": "frontend-replica-source-researcher",
            "description": "Captures source-page structure, state, content, interaction, and screenshot evidence.",
            "dependsOn": []
          },
          {
            "id": "frontend-replica-requirements-analyst",
            "agentID": "frontend-replica-requirements-analyst",
            "description": "Defines source-bound surface, interaction, content, asset, and rendered-parity requirements.",
            "dependsOn": [
              "frontend-replica-explorer",
              "frontend-replica-intent-analyst",
              "frontend-replica-source-researcher"
            ]
          },
          {
            "id": "frontend-replica-solution-architect",
            "agentID": "frontend-replica-solution-architect",
            "description": "Maps source evidence to target components, contracts, and verification regions.",
            "dependsOn": [
              "frontend-replica-requirements-analyst"
            ]
          },
          {
            "id": "frontend-replica-interface-modeler",
            "agentID": "frontend-replica-interface-modeler",
            "description": "Generates the sole source-bound project model and implementation contract consumed by Delivery Slice subjects.",
            "dependsOn": [
              "frontend-replica-solution-architect"
            ]
          },
          {
            "id": "frontend-replica-workload-analyst",
            "agentID": "frontend-replica-workload-analyst",
            "description": "Sizes source evidence, surface implementation, interaction, and visual verification work.",
            "dependsOn": [
              "frontend-replica-solution-architect"
            ]
          },
          {
            "id": "frontend-replica-implementer",
            "agentID": "frontend-replica-implementer",
            "description": "Implements the same source-bound surface in the target project.",
            "dependsOn": [
              "frontend-replica-interface-modeler",
              "frontend-replica-solution-architect",
              "frontend-replica-workload-analyst"
            ]
          },
          {
            "id": "frontend-replica-integrity-reviewer",
            "agentID": "frontend-replica-integrity-reviewer",
            "description": "Rejects missing regions, broken interactions, unsupported variance, and weak evidence.",
            "dependsOn": [
              "frontend-replica-implementer"
            ]
          },
          {
            "id": "frontend-replica-visual-reviewer",
            "agentID": "frontend-replica-visual-reviewer",
            "description": "Compares rendered target evidence against source regions and interaction states.",
            "dependsOn": [
              "frontend-replica-implementer"
            ]
          }
        ]
      }
    ],
    "projectedCapabilities": {
      "skills": 1,
      "tools": 14,
      "mcp": 17
    },
    "packageOwnedCapabilities": {
      "skills": 1,
      "tools": 2,
      "mcp": 0
    },
    "configuration": {
      "fields": 0,
      "required": 0
    }
  },
  {
    "identity": {
      "namespace": "builtin",
      "id": "frontend-innovate",
      "version": "2026.08.07.1",
      "digest": "eba3abda6ceda00312b3b1dac08952a39f9436f31c028d9cf39fe26ca78ade9c"
    },
    "name": "Frontend Innovate",
    "label": "Frontend Innovate",
    "description": "Evidence-backed product redesign, visual direction, implementation, and rendered proof through durable catalog facts and visible narrative Turn summaries.",
    "selectorSummary": "Use for evidence-backed frontend redesign and product innovation with rendered design proof.",
    "pillars": [
      "code"
    ],
    "agents": [
      {
        "id": "frontend-innovate-explorer",
        "label": "Frontend Innovation Explorer",
        "description": "Locates the current product surface, reusable assets, and implementation constraints.",
        "baseRole": "explore"
      },
      {
        "id": "frontend-innovate-intent-analyst",
        "label": "Frontend Innovation Intent Analyst",
        "description": "Classifies product intent, design ambition, evidence needs, and constraints.",
        "baseRole": "intent-analysis"
      },
      {
        "id": "frontend-innovate-requirements-analyst",
        "label": "Frontend Innovation Requirements Analyst",
        "description": "Defines observable product, component, data, interaction, and verification requirements.",
        "baseRole": "requirements"
      },
      {
        "id": "frontend-innovate-solution-architect",
        "label": "Frontend Innovation Solution Architect",
        "description": "Decomposes the selected direction into coherent product and implementation contracts.",
        "baseRole": "architect"
      },
      {
        "id": "frontend-innovate-experience-designer",
        "label": "Frontend Innovation Experience Designer",
        "description": "Produces evidence-backed design directions and a rendered source-editable design draft.",
        "baseRole": "frontend-design"
      },
      {
        "id": "frontend-innovate-source-researcher",
        "label": "Frontend Innovation Source Researcher",
        "description": "Investigates source pages, interaction states, information architecture, and visual evidence.",
        "baseRole": "frontend-research"
      },
      {
        "id": "frontend-innovate-implementer",
        "label": "Frontend Innovation Implementer",
        "description": "Implements the selected rendered design direction without inventing a parallel structure.",
        "baseRole": "build"
      },
      {
        "id": "frontend-innovate-visual-reviewer",
        "label": "Frontend Innovation Visual Reviewer",
        "description": "Reviews the rendered product against the selected design draft and evidence.",
        "baseRole": "visual-qa"
      },
      {
        "id": "frontend-innovate-deep-researcher",
        "label": "Frontend Innovation Researcher",
        "description": "Collects competitor, industry, and design-reference evidence.",
        "baseRole": "deep-research"
      },
      {
        "id": "frontend-innovate-fact-checker",
        "label": "Frontend Innovation Fact Checker",
        "description": "Verifies reference and product claims against evidence.",
        "baseRole": "fact-check"
      },
      {
        "id": "frontend-innovate-workload-analyst",
        "label": "Frontend Innovation Workload Analyst",
        "description": "Sizes design, implementation, evidence, and verification work.",
        "baseRole": "goal-workload-analyst"
      },
      {
        "id": "frontend-innovate-integrity-reviewer",
        "label": "Frontend Innovation Integrity Reviewer",
        "description": "Rejects generic, unevidenced, or structurally divergent design delivery.",
        "baseRole": "integrity"
      }
    ],
    "workflows": [
      {
        "id": "delivery",
        "label": "Frontend Innovate Delivery",
        "description": "Evidence-guided Frontend Innovate collaboration from investigation through delivery and independent review.",
        "nodes": [
          {
            "id": "frontend-innovate-explorer",
            "agentID": "frontend-innovate-explorer",
            "description": "Locates the current product surface, reusable assets, and implementation constraints.",
            "dependsOn": []
          },
          {
            "id": "frontend-innovate-intent-analyst",
            "agentID": "frontend-innovate-intent-analyst",
            "description": "Classifies product intent, design ambition, evidence needs, and constraints.",
            "dependsOn": []
          },
          {
            "id": "frontend-innovate-requirements-analyst",
            "agentID": "frontend-innovate-requirements-analyst",
            "description": "Defines observable product, component, data, interaction, and verification requirements.",
            "dependsOn": [
              "frontend-innovate-deep-researcher",
              "frontend-innovate-explorer",
              "frontend-innovate-intent-analyst",
              "frontend-innovate-source-researcher"
            ]
          },
          {
            "id": "frontend-innovate-solution-architect",
            "agentID": "frontend-innovate-solution-architect",
            "description": "Decomposes the selected direction into coherent product and implementation contracts.",
            "dependsOn": [
              "frontend-innovate-requirements-analyst"
            ]
          },
          {
            "id": "frontend-innovate-experience-designer",
            "agentID": "frontend-innovate-experience-designer",
            "description": "Produces evidence-backed design directions and a rendered source-editable design draft.",
            "dependsOn": [
              "frontend-innovate-solution-architect",
              "frontend-innovate-source-researcher"
            ]
          },
          {
            "id": "frontend-innovate-source-researcher",
            "agentID": "frontend-innovate-source-researcher",
            "description": "Investigates source pages, interaction states, information architecture, and visual evidence.",
            "dependsOn": []
          },
          {
            "id": "frontend-innovate-implementer",
            "agentID": "frontend-innovate-implementer",
            "description": "Implements the selected rendered design direction without inventing a parallel structure.",
            "dependsOn": [
              "frontend-innovate-experience-designer",
              "frontend-innovate-solution-architect",
              "frontend-innovate-workload-analyst"
            ]
          },
          {
            "id": "frontend-innovate-visual-reviewer",
            "agentID": "frontend-innovate-visual-reviewer",
            "description": "Reviews the rendered product against the selected design draft and evidence.",
            "dependsOn": [
              "frontend-innovate-implementer"
            ]
          },
          {
            "id": "frontend-innovate-deep-researcher",
            "agentID": "frontend-innovate-deep-researcher",
            "description": "Collects competitor, industry, and design-reference evidence.",
            "dependsOn": []
          },
          {
            "id": "frontend-innovate-fact-checker",
            "agentID": "frontend-innovate-fact-checker",
            "description": "Verifies reference and product claims against evidence.",
            "dependsOn": [
              "frontend-innovate-deep-researcher",
              "frontend-innovate-integrity-reviewer"
            ]
          },
          {
            "id": "frontend-innovate-workload-analyst",
            "agentID": "frontend-innovate-workload-analyst",
            "description": "Sizes design, implementation, evidence, and verification work.",
            "dependsOn": [
              "frontend-innovate-solution-architect"
            ]
          },
          {
            "id": "frontend-innovate-integrity-reviewer",
            "agentID": "frontend-innovate-integrity-reviewer",
            "description": "Rejects generic, unevidenced, or structurally divergent design delivery.",
            "dependsOn": [
              "frontend-innovate-implementer"
            ]
          }
        ]
      }
    ],
    "projectedCapabilities": {
      "skills": 0,
      "tools": 9,
      "mcp": 17
    },
    "packageOwnedCapabilities": {
      "skills": 0,
      "tools": 1,
      "mcp": 0
    },
    "configuration": {
      "fields": 1,
      "required": 1
    }
  },
  {
    "identity": {
      "namespace": "builtin",
      "id": "deep-research",
      "version": "2026.08.05.1",
      "digest": "989e2d91881e829fb00f321eb413ed58219d350054fb3c2c871f63e8c96fb251"
    },
    "name": "Deep Research",
    "label": "Deep Research",
    "description": "Multi-perspective source discovery, evidence curation, grounded outlining, cited drafting, independent citation review, and polished long-form reporting.",
    "selectorSummary": "Use for a broad or contested research question that requires multiple perspectives, deep sourcing, citations, synthesis, and a polished report.",
    "pillars": [
      "work"
    ],
    "agents": [
      {
        "id": "deep-research-planner",
        "label": "Deep Research Planner",
        "description": "Defines the research question, audience, perspective map, source policy, deliverable, and stopping conditions.",
        "baseRole": "delegated-worker"
      },
      {
        "id": "deep-research-knowledge-curator",
        "label": "Deep Research Knowledge Curator",
        "description": "Discovers distinct perspectives, asks perspective-specific questions, and builds a cited evidence dossier.",
        "baseRole": "deep-research"
      },
      {
        "id": "deep-research-outline-editor",
        "label": "Deep Research Outline Editor",
        "description": "Transforms selected evidence into a coherent, non-redundant hierarchy with section-level evidence assignments.",
        "baseRole": "delegated-worker"
      },
      {
        "id": "deep-research-draft-writer",
        "label": "Deep Research Draft Writer",
        "description": "Writes a complete, source-grounded draft whose inline citations map to the curated source index.",
        "baseRole": "delegated-worker"
      },
      {
        "id": "deep-research-citation-reviewer",
        "label": "Deep Research Citation Reviewer",
        "description": "Independently audits citation entailment, source quality, coverage, placement, synthesis, and uncertainty.",
        "baseRole": "fact-check"
      },
      {
        "id": "deep-research-report-writer",
        "label": "Deep Research Report Writer",
        "description": "Resolves the independent review and publishes canonical Markdown plus the visible final research report.",
        "baseRole": "build"
      }
    ],
    "workflows": [
      {
        "id": "multi-perspective-report",
        "label": "Multi-perspective Deep Research Report",
        "description": "Bound the question, curate perspective-led evidence, construct a grounded outline, draft with citations, audit citations, and publish a polished report.",
        "nodes": [
          {
            "id": "deep-research-planner",
            "agentID": "deep-research-planner",
            "description": "Publishes the bounded research charter and perspective plan.",
            "dependsOn": []
          },
          {
            "id": "deep-research-knowledge-curator",
            "agentID": "deep-research-knowledge-curator",
            "description": "Publishes the multi-perspective evidence dossier.",
            "dependsOn": [
              "deep-research-planner"
            ]
          },
          {
            "id": "deep-research-outline-editor",
            "agentID": "deep-research-outline-editor",
            "description": "Publishes the evidence-grounded article outline.",
            "dependsOn": [
              "deep-research-knowledge-curator"
            ]
          },
          {
            "id": "deep-research-draft-writer",
            "agentID": "deep-research-draft-writer",
            "description": "Publishes the complete cited draft.",
            "dependsOn": [
              "deep-research-outline-editor"
            ]
          },
          {
            "id": "deep-research-citation-reviewer",
            "agentID": "deep-research-citation-reviewer",
            "description": "Publishes the independent citation and synthesis review.",
            "dependsOn": [
              "deep-research-draft-writer"
            ]
          },
          {
            "id": "deep-research-report-writer",
            "agentID": "deep-research-report-writer",
            "description": "Publishes canonical Markdown and the visible final report.",
            "dependsOn": [
              "deep-research-citation-reviewer"
            ]
          }
        ]
      }
    ],
    "projectedCapabilities": {
      "skills": 2,
      "tools": 3,
      "mcp": 0
    },
    "packageOwnedCapabilities": {
      "skills": 2,
      "tools": 0,
      "mcp": 0
    },
    "configuration": {
      "fields": 0,
      "required": 0
    }
  },
  {
    "identity": {
      "namespace": "builtin",
      "id": "equity-research",
      "version": "2026.08.05.1",
      "digest": "a580ded3f60a3612f3a49e4d3602878cd789f1973a3d0529e6f22fd1bb719b9a"
    },
    "name": "Equity Research",
    "label": "Equity Research",
    "description": "Primary-source equity research from a dated evidence dossier through fundamentals, valuation, balanced thesis, numerical audit, and an investor-ready report.",
    "selectorSummary": "Use for public-company, industry, peer, valuation, catalyst, risk, and investment-thesis research that requires an auditable report.",
    "pillars": [
      "work"
    ],
    "agents": [
      {
        "id": "equity-research-planner",
        "label": "Equity Research Planner",
        "description": "Defines the dated research charter, investor question, peer boundary, source policy, and stopping conditions.",
        "baseRole": "delegated-worker"
      },
      {
        "id": "equity-source-analyst",
        "label": "Equity Source Analyst",
        "description": "Builds a dated primary-source dossier and normalized operating, financial, market, and peer evidence table.",
        "baseRole": "deep-research"
      },
      {
        "id": "equity-fundamentals-analyst",
        "label": "Equity Fundamentals Analyst",
        "description": "Explains growth, margins, cash conversion, capital intensity, balance-sheet quality, and peer positioning from selected evidence.",
        "baseRole": "delegated-worker"
      },
      {
        "id": "equity-valuation-analyst",
        "label": "Equity Valuation Analyst",
        "description": "Produces transparent comparable-company and intrinsic valuation ranges with sensitivities and explicit assumptions.",
        "baseRole": "delegated-worker"
      },
      {
        "id": "equity-thesis-analyst",
        "label": "Equity Thesis Analyst",
        "description": "Reconciles fundamentals and valuation into a balanced thesis, catalysts, risks, and bull/base/bear scenarios.",
        "baseRole": "delegated-worker"
      },
      {
        "id": "equity-fact-checker",
        "label": "Equity Fact Checker",
        "description": "Independently audits numerical traceability, dates, valuation arithmetic, source quality, and thesis support.",
        "baseRole": "fact-check"
      },
      {
        "id": "equity-report-writer",
        "label": "Equity Report Writer",
        "description": "Turns audited evidence into canonical Markdown and a visible investor-ready report without changing the underlying analysis.",
        "baseRole": "build"
      }
    ],
    "workflows": [
      {
        "id": "equity-research-report",
        "label": "Auditable Equity Research Report",
        "description": "Plan a dated public-equity study, curate sources, analyze fundamentals and valuation in parallel, form and audit the thesis, then publish the report.",
        "nodes": [
          {
            "id": "equity-research-planner",
            "agentID": "equity-research-planner",
            "description": "Publishes the bounded research charter.",
            "dependsOn": []
          },
          {
            "id": "equity-source-analyst",
            "agentID": "equity-source-analyst",
            "description": "Publishes the primary-source dossier and normalized evidence table.",
            "dependsOn": [
              "equity-research-planner"
            ]
          },
          {
            "id": "equity-fundamentals-analyst",
            "agentID": "equity-fundamentals-analyst",
            "description": "Publishes operating, financial-quality, and peer analysis.",
            "dependsOn": [
              "equity-source-analyst"
            ]
          },
          {
            "id": "equity-valuation-analyst",
            "agentID": "equity-valuation-analyst",
            "description": "Publishes valuation ranges, assumptions, and sensitivities.",
            "dependsOn": [
              "equity-source-analyst"
            ]
          },
          {
            "id": "equity-thesis-analyst",
            "agentID": "equity-thesis-analyst",
            "description": "Publishes the reconciled investment thesis and scenarios.",
            "dependsOn": [
              "equity-fundamentals-analyst",
              "equity-valuation-analyst"
            ]
          },
          {
            "id": "equity-fact-checker",
            "agentID": "equity-fact-checker",
            "description": "Publishes the independent factual and numerical audit.",
            "dependsOn": [
              "equity-thesis-analyst"
            ]
          },
          {
            "id": "equity-report-writer",
            "agentID": "equity-report-writer",
            "description": "Publishes canonical Markdown and the visible final report.",
            "dependsOn": [
              "equity-fact-checker"
            ]
          }
        ]
      }
    ],
    "projectedCapabilities": {
      "skills": 2,
      "tools": 3,
      "mcp": 0
    },
    "packageOwnedCapabilities": {
      "skills": 2,
      "tools": 0,
      "mcp": 0
    },
    "configuration": {
      "fields": 0,
      "required": 0
    }
  },
  {
    "identity": {
      "namespace": "builtin",
      "id": "review-debug",
      "version": "2026.08.05.1",
      "digest": "ae3e4a3c83f9326872238b685c1b1fcd9e67b7e170f0635b819bda481f8f9325"
    },
    "name": "Review & Debug",
    "label": "Review & Debug",
    "description": "Evidence-backed product review, root-cause debugging, product-source repair, and independent repair verification through durable catalog facts and visible narrative Turn summaries.",
    "selectorSummary": "Use for review of existing product changes, reproducible defect investigation, root-cause debugging, product repair, and repair verification.",
    "pillars": [
      "code"
    ],
    "agents": [
      {
        "id": "review-debug-evidence-investigator",
        "label": "Review & Debug Evidence Investigator",
        "description": "Reproduces the observed symptom, inventories runtime and repository evidence, and bounds the affected product surface.",
        "baseRole": "explore"
      },
      {
        "id": "review-debug-code-reviewer",
        "label": "Review & Debug Code Reviewer",
        "description": "Reviews the change and complete call graph for correctness, regressions, architectural violations, and causal clues.",
        "baseRole": "delegated-worker"
      },
      {
        "id": "review-debug-root-cause-investigator",
        "label": "Review & Debug Root Cause Investigator",
        "description": "Proves the causal chain from observable symptom through trigger and data flow to the underlying design or implementation fault.",
        "baseRole": "deep-research"
      },
      {
        "id": "review-debug-repair-implementer",
        "label": "Review & Debug Repair Implementer",
        "description": "Repairs the proven product root cause, removes the superseded path, adds regression tests, and verifies the changed surface.",
        "baseRole": "build"
      },
      {
        "id": "review-debug-integrity-reviewer",
        "label": "Review & Debug Integrity Reviewer",
        "description": "Independently reviews the repair diff and reruns the original reproduction and focused regression checks.",
        "baseRole": "delegated-worker"
      },
      {
        "id": "review-debug-visual-investigator",
        "label": "Review & Debug Visual Investigator",
        "description": "Reproduces a graphical defect in a real task-scoped preview and captures affected states, interactions, screenshots, and diagnostics.",
        "baseRole": "visual-qa"
      },
      {
        "id": "review-debug-visual-reviewer",
        "label": "Review & Debug Visual Reviewer",
        "description": "Independently verifies the repaired graphical state with fresh browser screenshots, interactions, focus paths, and diagnostics.",
        "baseRole": "visual-qa"
      }
    ],
    "workflows": [
      {
        "id": "review-only",
        "label": "Evidence-backed Review",
        "description": "Establish the exact requirement, review target, diff, and call-graph evidence, then issue an evidence-backed code review without implying product repair.",
        "nodes": [
          {
            "id": "review-debug-evidence-investigator",
            "agentID": "review-debug-evidence-investigator",
            "description": "Establishes the exact requirement, review target, diff, checks, and affected call graph.",
            "dependsOn": []
          },
          {
            "id": "review-debug-code-reviewer",
            "agentID": "review-debug-code-reviewer",
            "description": "Reviews the change and surrounding call graph against the established evidence.",
            "dependsOn": [
              "review-debug-evidence-investigator"
            ]
          }
        ]
      },
      {
        "id": "debug-repair",
        "label": "Product Debug and Repair",
        "description": "Reproduce the defect, independently review code and prove root cause, repair the product, and independently verify the repair.",
        "nodes": [
          {
            "id": "review-debug-evidence-investigator",
            "agentID": "review-debug-evidence-investigator",
            "description": "Reproduces the defect and establishes the exact evidence and affected surface.",
            "dependsOn": []
          },
          {
            "id": "review-debug-code-reviewer",
            "agentID": "review-debug-code-reviewer",
            "description": "Reviews the affected call graph and existing change for correctness and regression risk.",
            "dependsOn": [
              "review-debug-evidence-investigator"
            ]
          },
          {
            "id": "review-debug-root-cause-investigator",
            "agentID": "review-debug-root-cause-investigator",
            "description": "Proves the causal chain and explains why earlier paths did not cure the defect.",
            "dependsOn": [
              "review-debug-evidence-investigator"
            ]
          },
          {
            "id": "review-debug-repair-implementer",
            "agentID": "review-debug-repair-implementer",
            "description": "Repairs the proven root cause and adds focused regression coverage.",
            "dependsOn": [
              "review-debug-code-reviewer",
              "review-debug-root-cause-investigator"
            ]
          },
          {
            "id": "review-debug-integrity-reviewer",
            "agentID": "review-debug-integrity-reviewer",
            "description": "Independently reviews the diff and reruns the reproduction and regression checks.",
            "dependsOn": [
              "review-debug-repair-implementer"
            ]
          }
        ]
      },
      {
        "id": "visual-debug-repair",
        "label": "Graphical Product Debug and Repair",
        "description": "Reproduce a graphical defect, prove its code and visual causes, repair it, and independently verify fresh browser and repository evidence.",
        "nodes": [
          {
            "id": "review-debug-evidence-investigator",
            "agentID": "review-debug-evidence-investigator",
            "description": "Establishes the reported symptom, product boundary, repository evidence, and preview target.",
            "dependsOn": []
          },
          {
            "id": "review-debug-code-reviewer",
            "agentID": "review-debug-code-reviewer",
            "description": "Reviews the graphical implementation call graph and regression risk.",
            "dependsOn": [
              "review-debug-evidence-investigator"
            ]
          },
          {
            "id": "review-debug-root-cause-investigator",
            "agentID": "review-debug-root-cause-investigator",
            "description": "Proves the product data, event, rendering, or styling causal chain.",
            "dependsOn": [
              "review-debug-evidence-investigator"
            ]
          },
          {
            "id": "review-debug-visual-investigator",
            "agentID": "review-debug-visual-investigator",
            "description": "Captures the broken graphical states and interaction evidence in a real task-scoped preview.",
            "dependsOn": [
              "review-debug-evidence-investigator"
            ]
          },
          {
            "id": "review-debug-repair-implementer",
            "agentID": "review-debug-repair-implementer",
            "description": "Repairs the proven graphical product root cause and adds regression coverage.",
            "dependsOn": [
              "review-debug-code-reviewer",
              "review-debug-root-cause-investigator",
              "review-debug-visual-investigator"
            ]
          },
          {
            "id": "review-debug-integrity-reviewer",
            "agentID": "review-debug-integrity-reviewer",
            "description": "Independently reviews the repair diff and repository regression evidence.",
            "dependsOn": [
              "review-debug-repair-implementer"
            ]
          },
          {
            "id": "review-debug-visual-reviewer",
            "agentID": "review-debug-visual-reviewer",
            "description": "Verifies the repaired states with fresh screenshots, interactions, focus paths, and diagnostics.",
            "dependsOn": [
              "review-debug-repair-implementer"
            ]
          }
        ]
      }
    ],
    "projectedCapabilities": {
      "skills": 1,
      "tools": 3,
      "mcp": 17
    },
    "packageOwnedCapabilities": {
      "skills": 1,
      "tools": 0,
      "mcp": 0
    },
    "configuration": {
      "fields": 0,
      "required": 0
    }
  }
] as const
