// Auto-generated by script/generate-public-market.ts. Do not edit.
// Squad and role counts for every combination declared in src/content/squad-compositions.ts,
// resolved from the shipped catalog so published totals cannot drift from the packages.
//
// Typed rather than `as const`: these are counts a consumer does arithmetic over, and literal
// types would make `roleCount === sum(agentCount)` a type error instead of an assertion.

export type GeneratedCompositionSquad = {
  readonly namespace: string
  readonly id: string
  readonly displayLabel: { readonly root: string; readonly "zh-cn": string }
  readonly agentCount: number
  readonly workflowCount: number
}

export type GeneratedComposition = {
  readonly squads: readonly GeneratedCompositionSquad[]
  readonly extras: readonly GeneratedCompositionSquad[]
  readonly squadCount: number
  readonly roleCount: number
  readonly withExtrasSquadCount: number
  readonly withExtrasRoleCount: number
}

export const generatedSquadCompositions: Readonly<Record<string, GeneratedComposition>> =
{
  "research-to-paper": {
    "squads": [
      {
        "namespace": "builtin",
        "id": "scientific-research-design",
        "displayLabel": {
          "root": "Scientific Research Design",
          "zh-cn": "科学研究设计"
        },
        "agentCount": 4,
        "workflowCount": 1
      },
      {
        "namespace": "builtin",
        "id": "deep-research",
        "displayLabel": {
          "root": "Deep Research",
          "zh-cn": "深度研究"
        },
        "agentCount": 6,
        "workflowCount": 1
      },
      {
        "namespace": "builtin",
        "id": "data-analysis",
        "displayLabel": {
          "root": "Data Analysis & Business Insights",
          "zh-cn": "数据分析与商业洞察"
        },
        "agentCount": 7,
        "workflowCount": 1
      },
      {
        "namespace": "builtin",
        "id": "research-studio",
        "displayLabel": {
          "root": "Research Studio",
          "zh-cn": "研究工作室"
        },
        "agentCount": 5,
        "workflowCount": 3
      },
      {
        "namespace": "builtin",
        "id": "academic-paper-review",
        "displayLabel": {
          "root": "Academic Paper Review",
          "zh-cn": "学术论文审查"
        },
        "agentCount": 8,
        "workflowCount": 1
      },
      {
        "namespace": "builtin",
        "id": "office-delivery",
        "displayLabel": {
          "root": "Office Delivery",
          "zh-cn": "Office 交付"
        },
        "agentCount": 3,
        "workflowCount": 1
      }
    ],
    "extras": [
      {
        "namespace": "builtin",
        "id": "patent-landscape-prior-art",
        "displayLabel": {
          "root": "Patent Landscape and Prior Art",
          "zh-cn": "专利格局与现有技术"
        },
        "agentCount": 4,
        "workflowCount": 1
      },
      {
        "namespace": "builtin",
        "id": "browser-research-acceptance",
        "displayLabel": {
          "root": "Browser Research & Acceptance",
          "zh-cn": "浏览器研究与验收"
        },
        "agentCount": 3,
        "workflowCount": 1
      },
      {
        "namespace": "builtin",
        "id": "localization-adaptation",
        "displayLabel": {
          "root": "Localization & Adaptation",
          "zh-cn": "本地化与适配"
        },
        "agentCount": 4,
        "workflowCount": 1
      }
    ],
    "squadCount": 6,
    "roleCount": 33,
    "withExtrasSquadCount": 9,
    "withExtrasRoleCount": 44
  },
  "deal-due-diligence": {
    "squads": [
      {
        "namespace": "builtin",
        "id": "mergers-acquisitions-due-diligence",
        "displayLabel": {
          "root": "Mergers and Acquisitions Due Diligence",
          "zh-cn": "并购尽职调查"
        },
        "agentCount": 5,
        "workflowCount": 1
      },
      {
        "namespace": "builtin",
        "id": "forensic-accounting-investigations",
        "displayLabel": {
          "root": "Forensic Accounting Investigations",
          "zh-cn": "法务会计调查"
        },
        "agentCount": 5,
        "workflowCount": 1
      },
      {
        "namespace": "builtin",
        "id": "commercial-legal",
        "displayLabel": {
          "root": "Commercial Legal",
          "zh-cn": "商事法务"
        },
        "agentCount": 7,
        "workflowCount": 1
      },
      {
        "namespace": "builtin",
        "id": "tax-compliance",
        "displayLabel": {
          "root": "Tax Compliance",
          "zh-cn": "税务合规"
        },
        "agentCount": 7,
        "workflowCount": 1
      },
      {
        "namespace": "builtin",
        "id": "internal-audit-control-assurance",
        "displayLabel": {
          "root": "Internal Audit Control Assurance",
          "zh-cn": "内部审计与控制保障"
        },
        "agentCount": 5,
        "workflowCount": 1
      }
    ],
    "extras": [],
    "squadCount": 5,
    "roleCount": 29,
    "withExtrasSquadCount": 5,
    "withExtrasRoleCount": 29
  },
  "incident-to-knowledge": {
    "squads": [
      {
        "namespace": "builtin",
        "id": "service-reliability-incident-operations",
        "displayLabel": {
          "root": "Service Reliability Incident Operations",
          "zh-cn": "服务可靠性与事件运营"
        },
        "agentCount": 5,
        "workflowCount": 1
      },
      {
        "namespace": "builtin",
        "id": "digital-forensics-incident-investigation",
        "displayLabel": {
          "root": "Digital Forensics Incident Investigation",
          "zh-cn": "数字取证事件调查"
        },
        "agentCount": 5,
        "workflowCount": 1
      },
      {
        "namespace": "builtin",
        "id": "review-debug",
        "displayLabel": {
          "root": "Review & Debug",
          "zh-cn": "审查与调试"
        },
        "agentCount": 4,
        "workflowCount": 3
      },
      {
        "namespace": "builtin",
        "id": "knowledge-base-operations",
        "displayLabel": {
          "root": "Knowledge Base Operations",
          "zh-cn": "知识库运营"
        },
        "agentCount": 4,
        "workflowCount": 1
      }
    ],
    "extras": [],
    "squadCount": 4,
    "roleCount": 18,
    "withExtrasSquadCount": 4,
    "withExtrasRoleCount": 18
  },
  "product-launch": {
    "squads": [
      {
        "namespace": "builtin",
        "id": "product-management",
        "displayLabel": {
          "root": "Product Management",
          "zh-cn": "产品管理"
        },
        "agentCount": 4,
        "workflowCount": 1
      },
      {
        "namespace": "builtin",
        "id": "marketing-growth",
        "displayLabel": {
          "root": "Marketing & Growth Strategy",
          "zh-cn": "营销与增长战略"
        },
        "agentCount": 7,
        "workflowCount": 1
      },
      {
        "namespace": "builtin",
        "id": "seo-geo",
        "displayLabel": {
          "root": "SEO & Generative Engine Optimization",
          "zh-cn": "SEO 与生成式引擎优化"
        },
        "agentCount": 7,
        "workflowCount": 1
      },
      {
        "namespace": "builtin",
        "id": "product-video",
        "displayLabel": {
          "root": "Product Video Production",
          "zh-cn": "产品视频制作"
        },
        "agentCount": 4,
        "workflowCount": 1
      },
      {
        "namespace": "builtin",
        "id": "localization-adaptation",
        "displayLabel": {
          "root": "Localization & Adaptation",
          "zh-cn": "本地化与适配"
        },
        "agentCount": 4,
        "workflowCount": 1
      }
    ],
    "extras": [],
    "squadCount": 5,
    "roleCount": 26,
    "withExtrasSquadCount": 5,
    "withExtrasRoleCount": 26
  }
}
